export const PRODUCTS_MOCK = [
    {
        _id: 1,
        title: "title-01",
        category: "category-01",
        description: "description-01",
        image: "image-01",
        price: "price-01",
        stock: 1,
        trend: true,
        cart: false,
        favorite: false,
    },
    {
        _id: 2,
        title: "title-02",
        category: "category-02",
        description: "description-02",
        image: "image-02",
        price: "price-02",
        stock: 2,
        trend: false,
        cart: false,
        favorite: false,
    },
    {
        _id: 3,
        title: "title-03",
        category: "category-03",
        description: "description-03",
        image: "image-03",
        price: "price-03",
        stock: 3,
        trend: true,
        cart: false,
        favorite: false,
    },
    {
        _id: 4,
        title: "title-04",
        category: "category-03",
        description: "description-04",
        image: "image-04",
        price: "price-04",
        stock: 4,
        trend: true,
        cart: false,
        favorite: false,
    },
    {
        _id: 5,
        title: "title-05",
        category: "category-01",
        description: "description-05",
        image: "image-05",
        price: "price-05",
        stock: 5,
        trend: false,
        cart: false,
        favorite: false,
    },
    {
        _id: 6,
        title: "title-06",
        category: "category-02",
        description: "description-06",
        image: "image-06",
        price: "price-06",
        stock: 6,
        trend: true,
        cart: false,
        favorite: false,
    },
    {
        _id: 7,
        title: "title-07",
        category: "category-03",
        description: "description-07",
        image: "image-07",
        price: "price-07",
        stock: 7,
        trend: false,
        cart: false,
        favorite: false,
    },
    {
        _id: 8,
        title: "title-08",
        category: "category-02",
        description: "description-08",
        image: "image-08",
        price: "price-08",
        stock: 8,
        trend: false,
        cart: false,
        favorite: false,
    },
    {
        _id: 9,
        title: "title-09",
        category: "category-01",
        description: "description-09",
        image: "image-09",
        price: "price-09",
        stock: 9,
        trend: false,
        cart: false,
        favorite: false,
    },
    {
        _id: 10,
        title: "title-010",
        category: "category-02",
        description: "description-010",
        image: "image-010",
        price: "price-010",
        stock: 10,
        trend: true,
        cart: false,
        favorite: false,
    }
]